platform: 'ios'
connection_options:
  napalm:
    extras:
      optional_args:
        dest_file_system: 'flash0:'
        timeout: 60
        allow_agent: ios
        global_delay_factor: 10
        device_type: 'cisco_ios_telnet'